-- Run this once in Supabase: Dashboard > SQL Editor > New query.
-- Project data is kept as JSONB so the existing project-sheet fields can evolve
-- without exposing one user's projects to another.

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    project jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists projects_user_id_idx on public.projects (user_id);
create index if not exists projects_updated_at_idx on public.projects (updated_at desc);

create or replace function public.set_projects_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_projects_updated_at();

alter table public.projects enable row level security;

grant select, insert, update, delete on public.projects to authenticated;
grant usage, select on sequence public.projects_id_seq to authenticated;

create policy "Users can read their own projects"
on public.projects for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own projects"
on public.projects for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own projects"
on public.projects for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own projects"
on public.projects for delete to authenticated
using ((select auth.uid()) = user_id);
